#pragma once
//Подключаем заголовочный файл
#include"Functions.h"


const int
CONTINUE = 1,       //Продолжение
DESCENDING = 2,     //По убыванию
BACK = 0,           //Назад
ASCENDING = 1,      //По возрастанию
MAN_GENDER = 1,     //Мкжской пол
WOMAN_GENDER = 2,   //Женский пол
MIN_AGE = 0,        //Минимальный возраст для поиска
MAX_AGE = 99,       //Максимальный возрст для поиска
SALT_SIZE = 16,     // длина соли
SYMBOLS_SIZE = 62,  // набор символов, из которых генерируется соль
MIN_SYMBOLS_FOR_INPUT = 4,  //Минимум вводимых символов
RESERVE_AMOUNT_OF_ACCOUNTS = 100,  //Резерв количества аккаунтов
RESERVE_AMOUNT_OF_PATIENT = 1000,  //Резерв количества пациентов
JANUARY = 1,               //Январь
FEBRUARY = 2,              //Февраль
MARCH = 3,                 //Март
APRIL = 4,                 //Апрель
MAY = 5,                   //Май  
JUNE = 6,                  //Июнь
JULY = 7,                  //Июль
AUGUST = 8,                //Август
SEPTEMBER = 9,             //Сентябрь
OCTOBER = 10,              //Октябрь
NOVEMBER = 11,             //Ноябрь
DECEMBER = 12,             //Декабрь
BORDER_DAYS_START = 1,     //Начальня граница дней
BORDER_DAYS_END = 31,      //Конечная граница дней
BORDER_MONTH_START = 1,    //Начальная граница месяцев
BORDER_MONTH_END = 12,     //Конечная граница месяцев
BORDER_YEAR_END = 2023,    //Конечная граница годов
BORDER_YEAR_START = 1920,  //Начальная граница годов
YES = 1,                   //Да
NO = 2,                    //Нет
FEBRUARURY_DAYS = 28,      //Последний день февраля
FULL_MONTH = 31,           //Месяц с 31 днем
NO_FULL_MONTH = 30,        //Месяц с 30 днями
BACK_TO_SEARCH_MENU = 0,   //Возврат в меню поиска
REPEAT = 1,                //Продолжение
BACK_TO_ADMIN_MENU = 0,    //Возврат в меню админа
KEY_ENTER = 13,            //Клавиша ENTER
KEY_DELETE = 8,            //Клавиша DELETE
REGISTRATION = 3,          //Вариант с регистарцией
FIRST_PATIENT =1,
DATA_EMPTY = 0;            //Данные не найдены

const string
BACK_TO_AUTORIZATION = "0",
NO_PATIENTS = "\nПациентов нет\n",
PATIENTS_NO = "В данное время этот выбор меню недоступен, т.к. пациентов нет\n",
ADMIN_MAIN = "mainAdmin",            
MAN = "мужской",
WOMAN = "женский",
NOACCESS = "0",
ACCOUNTS = "Аккаунты:\n",
USER_FUNCTIONALITY = "Вы находитесь в функционале пользователя\n\n",
ADMIN_FUNCTIONALITY = "Вы находитесь в функционале администратора\n\n",
MAIN_ADMIN_FUNCTIONALITY = "Вы находитесь в функционале главного администратора\n\n",
DATA_IS_EMPTY = "Данные пусты!\n",
CONFIRMATION_EXIT_FROM_ACCOUNT = "Вы уверены, что хотите выйти из аккаунта ? \n1.Да\n2.Нет\n << ",
EXIT_FROM_PROGRAM = "Вы вышли из программы\nВсего доброго!\n",
ACCOUNT = "аккаунт",
PATIENT = "пациент",
DATA_NOT_ADD = "Пациент не был добавлен\n",
LOGIN_AND_PASSWORD_INPUT = "Введите ваш логин и пароль или вернитесь назад - '0'\n",
LOGIN_INPUT = "Логин << ",
PASSWORD_INPUT = "Пароль << ",
INCORRECT_LOGIN_AND_PASSWORD_INPUT = "Неверно введен логин или пароль\nПовторите ввод\n\n",
ACCESS = "1",
NO_ACCESS = "0",
ADMIN = "admin",
USER = "user",
LOGIN_IS_BUSY = "Пользователь с таким логином уже существует\n",
REPEAT_PASSWORD = "Повторите ввод пароля\n<< ",
INPUT_PASSWORD = "\nВведите пароль состоящий из 0 - 9, A - Z, a - z,  >6 символов\n<< ",
INPUT_LOGIN = "\nВведите логин состоящий из 0 - 9, A - Z, a - z,  >6 символов\n<< ",
BACK_ON_0 = " 0.Вернуться назад\n\n",
INPUT_REPEAT_PASSWORD = "Повторите пароль\n << ",
INPUT_DATA_FOR_REGIST = "Заполните данные:\n",
PASSWORD_SUCCESSFULLY_CHANGED = "Пароль успешно изменен\n",
PASSWORDS_DO_NOT_MATCH = "Пароли не совпадают\n",
PASSWORD_HAS_NOT_BEEN_CHANGED = "Пароль не был изменен\n",
INPUT_SURNAME = "\nВведите фамилию: \n<< ",
INPUT_NAME = "\nВведите имя: \n<< ",
INPUT_PATRONYMIC = "\nВведите отчество: \n<< ",
INPUT_GENDER = "\nВыберите пол: \n<< ",
INPUT_DATA_OF_BIRTH = "\nВведите дату рождения\n<< ",
INPUT_TOWN = "\nВведите место жительство: \n<< ",
INPUT_PHONE_NUMBER = "\nВведите номер телефона: \n<< ",
INPUT_DIAGNOSIS = "\nВведите диагноз: \n<< ",
DATA_HAS_NOT_BEEN_CHANGED = "Данные не были изменены\n\n",
LETTERS_SYMBOLS = "йцукенгшщзхъэждлорпавыфячсмитьбюЙЦУКЕНГШЩЗХЪЭЖДЛОРПАВЫФЯЧСМИТЬБЮ-",
LOGIN_LETTERS_SYMBOLS = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm",
FIND_DATA_AFTER_SEARCH = "\nНайденные данные по вашему поиску : \n",
WHO_AGE_AND_DIAGNOSIS = "Введите старше скольки лет хотите вывести пациентов и с каким диагнозом?\n",
SURNAME = "фамилии",
PATRONYMIC = "отчество",
GENDER = "пол",
PHONE_NUMBER = "номер телефона",
NAME = "имени",
TOWN = "месту жительства",
DIAGNOSIS = "диагнозу",
DATA_NOT_FOUND = "\nДанные по вашему поиску не найдены или некоректно введены.\n 1. Повторить данный поиск\n0. Вернуться в меню поиска:\n<< ",
NUMBER_SYMBOLS = "+0123456789",
NO_NONRESIDENT = "Минск",
ALL_PATIENTS = "Все пациенты\n",
EXIT_FROM_INPUT = "0",
LOGIN = "логин",
PASSWORD = "пароль",
INCORRECT_INPUT = "Некорректный ввод!\nПовторите попытку и введите корректные данные\n<< ",
INPUT_DATA = "Заполните данные:\n",
INPUT_ADD_SURNAME = "Фамилия << ",
INPUT_ADD_NAME = "Имя << ",
INPUT_ADD_PATRONYMIC = "Отчество << ",
INPUT_ADD_GENDER = "Пол << ",
INPUT_ADD_DATE_BIRTH = "Дата рождения:\n",
INPUT_ADD_TOWN = "Место жительства << ",
INPUT_ADD_PHONE = "Номер телефона << ",
INPUT_ADD_DIAGNOSIS = "Диагноз << ",
DATA_HAS_ADD = "Данные добавлены\n",
DATA_NOT_HAS_ADD = "Данные не были добавлены\n",
CONFIRMATION_ADD = "Вы уверены что хотите добавить данные \n1.Да\n2.Нет\n<<",
INCORRECT_DATA_OF_BIRTH = "Неверно введены дата рождения. Повторите ввод\n",
PATIENT_DELETE = "Пациент удален\n",
PATIENT_NOT_DELETE = "Пациент не был удален\n",
ACCOUNT_DELETE = "Аккаунт удален\n",
ACCOUNT_NOT_DELETE = "Аккаунт не был удален\n",
CONFIRMATION_DELETE_ACCOUNT = "Вы уверены , что хотите удалить этот аккаунт?\n1.Да\n2.Нет\n<< ",
CONFIRMATION_DELETE_PATIENT = "Вы уверены , что хотите удалить этого пациента?\n1.Да\n2.Нет\n<< ",
NO_ACTIVATION_ACCOUNTS = "\nНеактивированные аккаунта:\n",
WHAT_ACCOUNT_ACTIVATION = "\nКакой аккаунт хотите активировать << ",
CONFIRMATION_ACTIVATION = "\nВы уверены, что хотите активировать данный аккаунт?\n1. Да\n2. Нет\n<< ",
CONFIRMATION_BLOCKING = "\nВы уверены, что хотите заблокировать данный аккаунт?\n1. Да\n2. Нет\n<< ",
ACTIVATION_REQUESTS = "Заявки на активацию:\n",
BLOCKING_REQUESTS = "Заявки на блокировки:\n",
ACCOUNT_NOT_ACTIVATED = "Данный акккаунт не был активирован\n\n",
ENTER_APPLICATION_NUMBER = "\nВвведите номер заявки для одобрения << ",
ENTER_FOR_BLOCKING = "\nВвведите номер заявки для блокировка << ",
ACCOUNT_ACTIVATED = "\nАккаунт активирован\n\n",
ACCOUNT_BLOCKING = "\nАккаунт заблокирован\n\n",
NO_APPLICATION_REQUESTS = "Заявок на активацию аккаунта нет\n\n",
NO_BLOCK_REQUESTS = "Заявок на блокировка аккаунта нет\n\n",
ACCES = "доступ",
ROLE = "роль",
DATA_BEEN_CHANGED = "Данные изменены\n",
DATA_ACCOUNT_FOR_EDIT = "Данные аккаунта который хотите изменить\n",
YOU_NOT_EDIT_ACCOUNT = "Вы не можете отредактировать свой аккаунт\n",
CONFIRMATION_EXIT_FROM_PROGRAM =  "Вы уверены, что хотите выйти из программы?\n1. Да\n2. Нет\n<< ",
SORT_FOR_AGE_DESCENDING = "Пациенты отсортированы по возрасту(99-0)\n",
SORT_FOR_AGE_ASCENDING = "Пациенты отсортированы по возрасту(0-99)\n",
MENU_SORT_FOR_AGE = "Сортировка данных по возрасту:\n1. По возрастанию\n2. По убыванию\n0. Назад\n<< ",
ERROR_OPEN_FAIL =  "Ошибка открытия файла\n\n",
WITH_ACCESS = "С доступом",
WITHOUT_ACCESS = "Без доступа",
NOT_DELETE_MAIN_ADMIN = "\nВы не можете удалить свой аккаунт главного администратора\n",
MENU_CONFIRMATION_REGISTRATION = "Вы уверены что хотите зарегистрироваться \n1.Да\n2.Нет\n<<",
PASSWORDS_DO_MOT_MATCH = "\nПароли не совпадают\n",
YOU_ARE_REGISTERED = "\nВаша заявка на регистрацию отправлена на рассмотрение администратору\n",
INCCORECT_INPUT_DATE_OF_BIRTH = "Дата рождения не соответсвует календарному. Повторите попытку и введите корректные данные\n",
DAY = "\nДень << ",
MONTH = "Месяц << ",
YEAR = "Год << ",
YOU_CANNOT_BLOCK_YOUR_ACCOUNT = "Вы не можете заблокировать свой аккаунт\n",
YOU_CANNOT_DISABLE_MAIN_ADMIN = "Вы не можете заблокировать аккаунт главного администратора\n",
ACCOUNT_NOT_BLOCKED = "Аккаунт не был заблокирован\n",
REGISTR_AS_MAIN_ADMIN = "Cоздайте програмнно файл с учетными записями для этого зарегистрируйтесь в качестве главного админа",
SEARCH_NOT_FOUND = "По вашему запросу данные не найдены, проверьте корректность введеных данных\n\n",
DATA_OF_BIRTH = " дата рождения ",
YOU_HAVE_CREATED_FILE_AND_REGISTERED_MAIN_ADMIN = "Вы создали файл с учетными записями и зарегистрировались в качестве главного администратора\n",
NOT_NONRESIDENT_PATIENTS = "Иногородних пациентов нет\n\n",
NO_PATIENTS_GENDER = "Пациентов с выбранным гендерным полом нет\n",
NONRESIDENT_PATIENTS = "Иногородние пациенты\n\n";
